name: wotlk_cookbook
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
   git:
     url: https://github.com/Davenchy/flutter_launcher_icons.git
     ref: fixMinSdkParseFlutter2.8
  flutter_lints: ^2.0.0
  logging: ^1.0.2
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1

flutter_icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets: 
    - packages/wotlk_cookbook/assets/guides/01.json
  fonts:
    - family: Lifecraft
      fonts:
        - asset: assets/fonts/lifecraft.ttf
          style: normal
    - family: Areal
      fonts:
        - asset: assets/fonts/AREAL.TTF
